# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

likelihood_C <- function(media, correctedFixTime, tim, sum_correctedFixTime, stateStep, changeMatrix, prStates, sigma, changeUp, changeDown) {
    .Call(`_likelihood_likelihood_C`, media, correctedFixTime, tim, sum_correctedFixTime, stateStep, changeMatrix, prStates, sigma, changeUp, changeDown)
}

rcpp_hello_world <- function() {
    .Call(`_likelihood_rcpp_hello_world`)
}

